apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-calculator
  labels:
    app: simple-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-calculator
  template:
    metadata:
      labels:
        app: simple-calculator
    spec:
      containers:
      - name: calculator
        image: simple-calculator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
