apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
  labels:
    app: simple-calculator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: simple-calculator
