apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-calculator
  namespace: argocd
  labels:
    app: simple-calculator
spec:
  project: default
  source:
    repoURL: https://github.com/Chaitanya299/DevOps-calci.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
